import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar/Navbar";
import Sidebar from "@/components/layout/sidebar/Sidebar";
import WidthShow from "@/components/layout/widthShow/WidthShow";
import { SidebarProvider } from "@/context/SidebarContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider defaultOpen={true}>
          <Navbar />
          <div className="flex pt-[50px]">
            <Sidebar />
            <div className=" bg-slate-50 w-full p-4 min-h-[calc(100vh-50px)] z-40">
              {children}
            </div>
          </div>
          <WidthShow />
        </SidebarProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
